/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIs;

import java.awt.List;
import java.io.File;
import java.util.Collections;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author ADMIN
 */
public class SentDocument extends javax.swing.JFrame {

    /**
     * Creates new form SentDocument
     */
    DefaultListModel<String> listModel;
    
    //thay đổi đường dẫn để chọn vị trí lưu file
    private String fileDirectory = "D:\\Data\\DataJava\\";
    
    public SentDocument() {
        initComponents();        
        listModel = new DefaultListModel<>();
        jList1.setModel(listModel);
        
        //Hiển thị danh sách tên file lên giao diện
        displayFileNameInList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jChonFile = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jXoaFile = new javax.swing.JButton();
        jBReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/logo-ngang.png"))); // NOI18N

        jChonFile.setText("Chọn file");
        jChonFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChonFileActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jXoaFile.setText("Xoa file");
        jXoaFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXoaFileActionPerformed(evt);
            }
        });

        jBReset.setText("Tải lại");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jXoaFile, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBReset, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jChonFile)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jChonFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXoaFile)
                    .addComponent(jBReset))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayFileNameInList(){
        listModel.clear();
        
        File folder = new File(fileDirectory);
        File[] listFiles = folder.listFiles();
        if(listFiles != null)
            for(File file : listFiles){
                if(file.isFile()){
                    listModel.addElement(file.getName());
                }
            }
    }
    
    private void jChonFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChonFileActionPerformed
        // TODO add your handling code here:
        JFileChooser chosserFile = new JFileChooser();
        int returnValue = chosserFile.showOpenDialog(null);
        
        if(returnValue == JFileChooser.APPROVE_OPTION){
            File selectedFile = chosserFile.getSelectedFile();
            String fileName = selectedFile.getName();
                        
            listModel.addElement(fileName);
                        
            
            // Sao chép file vào địa chỉ mong muốn
            try{
                File destinationFile = new File(fileDirectory + fileName);
                java.nio.file.Files.copy(selectedFile.toPath(), destinationFile.toPath());
            }
            catch(Exception e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "File đã được gửi");
            }
            displayFileNameInList();
        }
    }//GEN-LAST:event_jChonFileActionPerformed

    private void jXoaFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXoaFileActionPerformed
        // TODO add your handling code here:
        //xóa file đã chọn trên giao diện
        int selectedIndex = jList1.getSelectedIndex();
        if(selectedIndex != -1){
            String fileNameToRemove = listModel.getElementAt(selectedIndex);
            listModel.remove(selectedIndex);
            
            //Xóa file trong fileDirectory
            File fileToRemove = new File(fileDirectory + fileNameToRemove);
            if(fileToRemove.exists()){
                fileToRemove.delete();
            }
            displayFileNameInList();
        }
        
        
    }//GEN-LAST:event_jXoaFileActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SentDocument.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SentDocument.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SentDocument.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SentDocument.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SentDocument().setVisible(true);
            }
        });
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBReset;
    private javax.swing.JButton jChonFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jXoaFile;
    // End of variables declaration//GEN-END:variables
}
